In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("customers-100.csv")
df.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(283)437-3886x88321,999-728-1637,NaN,NaN,NaN
6,7.0,EA4d384DfDbBf77,Darren,NaN,"Lester, Woodard and Mitchell",Lake Ana,NaN,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,24-08-2021,https://www.le.com/
7,8.0,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,12-04-2021,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,13-01-2020,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,08-11-2021,https://arias.com/

In [8]:
df = pd.read_csv("customers-100.csv", skiprows=15)
df.head()

,15,6fEaA1b7cab7B6C,Faith,Lutz,Carter-Hancock,Burchbury,Singapore,(781)861-7180x8306,207-185-3665,cassieparrish@blevins-chapman.net,26-01-2022,http://stevenson.org/
0,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,12-04-2022,http://acosta.org/
1,17,a5DC21AE3a21eaA,Caroline,Foley,Winters-Mendoza,West Adriennestad,Western Sahara,936.222.4746x9924,001-469-948-6341x359,holtgwendolyn@watson-davenport.com,10-03-2021,http://www.benson-roth.com/
2,18,F8Aa9d6DfcBeeF8,Greg,Mata,Valentine LLC,Lake Leslie,Mozambique,(701)087-2415,(195)156-1861x26241,jaredjuarez@carroll.org,26-03-2022,http://pitts-cherry.com/
3,19,F160f5Db3EfE973,Clifford,Jacobson,Simon LLC,Harmonview,South Georgia and the South Sandwich Islands,001-151-330-3524x0469,(748)477-7174,joseph26@jacobson.com,24-09-2020,https://mcconnell.com/
4,20,0F60FF3DdCd7aB0,Joanna,Kirk,Mays-Mccormick,Jamesshire,French Polynesia,(266)131-7001x711,(283)312-5579x11543,tuckerangie@salazar.net,24-09-2021,https://www.camacho.net/

In [7]:
df = pd.read_csv("customers-100.csv", header=15)
df

,15,6fEaA1b7cab7B6C,Faith,Lutz,Carter-Hancock,Burchbury,Singapore,(781)861-7180x8306,207-185-3665,cassieparrish@blevins-chapman.net,26-01-2022,http://stevenson.org/
0,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,12-04-2022,http://acosta.org/
1,17,a5DC21AE3a21eaA,Caroline,Foley,Winters-Mendoza,West Adriennestad,Western Sahara,936.222.4746x9924,001-469-948-6341x359,holtgwendolyn@watson-davenport.com,10-03-2021,http://www.benson-roth.com/
2,18,F8Aa9d6DfcBeeF8,Greg,Mata,Valentine LLC,Lake Leslie,Mozambique,(701)087-2415,(195)156-1861x26241,jaredjuarez@carroll.org,26-03-2022,http://pitts-cherry.com/
3,19,F160f5Db3EfE973,Clifford,Jacobson,Simon LLC,Harmonview,South Georgia and the South Sandwich Islands,001-151-330-3524x0469,(748)477-7174,joseph26@jacobson.com,24-09-2020,https://mcconnell.com/
4,20,0F60FF3DdCd7aB0,Joanna,Kirk,Mays-Mccormick,Jamesshire,French Polynesia,(266)131-7001x711,(283)312-5579x11543,tuckerangie@salazar.net,24-09-2021,https://www.camacho.net/
...,...,...,...,...,...,...,...,...,...,...,...,...
80,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
81,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
82,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
83,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
84,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [9]:
df = pd.read_csv("customers-100.csv", header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
1,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
2,2,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df = pd.read_csv("customers-100.csv", header=None, names=["Col1", "Col2", "Col3", "Col4", "Col5", "Col6", "Col7", "Col8", "Col9", "Col10", "Col11"])
df.head()

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11
Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
2,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df = pd.read_csv("customers-100.csv", nrows=10)
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(283)437-3886x88321,999-728-1637,NaN,NaN,NaN
6,7.0,EA4d384DfDbBf77,Darren,NaN,"Lester, Woodard and Mitchell",Lake Ana,NaN,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,24-08-2021,https://www.le.com/
7,8.0,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,12-04-2021,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,13-01-2020,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,08-11-2021,https://arias.com/

In [17]:
df = pd.read_csv("customers-100.csv", na_values=["Sheryl","Baxter", "Chile"])
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,NaN,NaN,Rasmussen Group,NaN,NaN,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/

In [25]:
df = pd.read_csv("customers-100.csv", na_values={
        'First Name': ["Sheryl"],
        'Company': ["Rasmussen Group", "Browning-Simon"]}
    )
df.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,NaN,Baxter,NaN,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(283)437-3886x88321,999-728-1637,NaN,NaN,NaN
6,7.0,EA4d384DfDbBf77,Darren,NaN,"Lester, Woodard and Mitchell",Lake Ana,NaN,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,24-08-2021,https://www.le.com/
7,8.0,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,12-04-2021,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,NaN,Meyers,NaN,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,13-01-2020,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,08-11-2021,https://arias.com/

In [28]:
df.to_csv('firstFile1.csv')

In [29]:
df.to_csv("newFile.csv", index=False)

In [32]:
df.to_csv("newFile1.csv", columns=["First Name","Company","Email"], index=False)

In [34]:
df.to_csv("newFile2.csv", header=False)

In [35]:
df = pd.read_excel("file_example.xls", "Data")
df

       Name  Gender        Country  Age    Id
0     Dulce  Female  United States   32  1562
1      Mara  Female  Great Britain   25  1582
2    Philip    Male         France   36  2587
3  Kathleen  Female  United States   25  3549
4   Nereida  Female  United States   58  2468
5    Gaston    Male  United States   24  2554
6      Etta  Female  Great Britain   56  3598
7   Earlean  Female  United States   27  2456
8  Vincenza  Female  United States   40  6548

In [36]:
df.to_excel("newExcel.xlsx")

In [37]:
df.to_excel("newExcel.xlsx", index=False)

In [39]:
df.to_excel("newExcel.xlsx", sheet_name="Data", index=False)

In [40]:
df.to_excel("newExcelFile.xlsx", sheet_name="Data", index=False, startrow=2, startcol=3)

In [42]:
df1 = pd.DataFrame({
    'stocks': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df2 = pd.DataFrame({
    'day': ['1/1/2017', '1/2/2017', '1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']
})

df1

  stocks  price     pe    eps
0  GOOGL    845  30.37  27.82
1    WMT     65  14.26   4.61
2   MSFT     64  30.97   2.12

In [43]:
df2

        day  temperature  event
0  1/1/2017           32   Rain
1  1/2/2017           35  Sunny
2  1/3/2017           28   Snow

In [44]:
df1.to_excel("stock.xlsx", sheet_name="price")

In [45]:
df1.to_excel("stock.xlsx", sheet_name="price", index=False)

In [46]:
with pd.ExcelWriter('trippleData.xlsx') as writer:
                    df1.to_excel(writer, sheet_name="Stocks")
                    df2.to_excel(writer, sheet_name="Temperature")
                    df.to_excel(writer, sheet_name="Employee", index=False)