In [1]:
import pandas as pd

# Handling Missing Data

In [4]:
df = pd.read_csv('customers-100.csv')
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/

In [5]:
df['Subscription Date']

0     24-08-2020
1     23-04-2021
2            NaN
3            NaN
4     17-04-2021
         ...
95    30-01-2022
96    10-07-2021
97    18-09-2021
98    11-08-2021
99    11-03-2020
Name: Subscription Date, Length: 100, dtype: object

In [6]:
type(df['Subscription Date'][0])

str

In [7]:
df = pd.read_csv('customers-100.csv', parse_dates=['Subscription Date'])
type(df['Subscription Date'][0])

C:\Users\91801\AppData\Local\Temp\ipykernel_20612\149584795.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv('customers-100.csv', parse_dates=['Subscription Date'])

pandas._libs.tslibs.timestamps.Timestamp

In [8]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaT,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [9]:
df2 = df.fillna("0")
df2.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,0,Chile,0,397.884.0519x718,zunigavanessa@smith.info,2020-08-24 00:00:00,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,0,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23 00:00:00,http://www.hobbs.com/
2,0,0,0,0,0,0,0,0,0,beckycarr@hogan.com,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0
4,5.0,053d585Ab6b3159,Joanna,0,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17 00:00:00,https://goodwin-ingram.com/
5,0,0,0,0,0,0,0,(283)437-3886x88321,999-728-1637,0,0,0
6,7.0,EA4d384DfDbBf77,Darren,0,"Lester, Woodard and Mitchell",Lake Ana,0,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24 00:00:00,https://www.le.com/
7,8.0,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12 00:00:00,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13 00:00:00,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08 00:00:00,https://arias.com/

In [11]:
df3 = df.fillna({
    'Last Name': "No Last name",
    'Company': "No Company",
    'City': "No City",
    'Country': "No Country"
})
df3.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,No City,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,No Company,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,NaN,NaN,NaN,No Last name,No Company,No City,No Country,NaN,NaN,beckycarr@hogan.com,NaT,NaN
3,NaN,NaN,NaN,No Last name,No Company,No City,No Country,NaN,NaN,NaN,NaT,NaN
4,5.0,053d585Ab6b3159,Joanna,No Last name,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,NaN,NaN,NaN,No Last name,No Company,No City,No Country,(283)437-3886x88321,999-728-1637,NaN,NaT,NaN
6,7.0,EA4d384DfDbBf77,Darren,No Last name,"Lester, Woodard and Mitchell",Lake Ana,No Country,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8.0,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [13]:
df.head(6)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaT,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(283)437-3886x88321,999-728-1637,NaN,NaT,NaN

In [12]:
df4 = df.fillna(method='ffill')
df4.head(10)

C:\Users\91801\AppData\Local\Temp\ipykernel_20612\2814763064.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df4 = df.fillna(method='ffill')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,Rasmussen Group,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,2.0,1Ef7b82A4CAAD10,Preston,Lozano,Rasmussen Group,East Jimmychester,Djibouti,5153435776,686-620-1820x944,beckycarr@hogan.com,2021-04-23,http://www.hobbs.com/
3,2.0,1Ef7b82A4CAAD10,Preston,Lozano,Rasmussen Group,East Jimmychester,Djibouti,5153435776,686-620-1820x944,beckycarr@hogan.com,2021-04-23,http://www.hobbs.com/
4,5.0,053d585Ab6b3159,Joanna,Lozano,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,5.0,053d585Ab6b3159,Joanna,Lozano,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),(283)437-3886x88321,999-728-1637,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
6,7.0,EA4d384DfDbBf77,Darren,Lozano,"Lester, Woodard and Mitchell",Lake Ana,Slovakia (Slovak Republic),(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8.0,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [14]:
df4 = df.fillna(method='bfill')
df4.head(10)

C:\Users\91801\AppData\Local\Temp\ipykernel_20612\3031610167.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df4 = df.fillna(method='bfill')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Jimmychester,Chile,5153435776,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,"Martin, Lang and Andrade",East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,5.0,053d585Ab6b3159,Joanna,Mullen,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,beckycarr@hogan.com,2021-04-17,https://goodwin-ingram.com/
3,5.0,053d585Ab6b3159,Joanna,Mullen,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
4,5.0,053d585Ab6b3159,Joanna,Mullen,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,7.0,EA4d384DfDbBf77,Darren,Mullen,"Lester, Woodard and Mitchell",Lake Ana,Bulgaria,(283)437-3886x88321,999-728-1637,tgates@cantrell.com,2021-08-24,https://www.le.com/
6,7.0,EA4d384DfDbBf77,Darren,Mullen,"Lester, Woodard and Mitchell",Lake Ana,Bulgaria,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8.0,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [15]:
df6 = df.fillna(method='ffill', axis='columns')
df6.head(7)

C:\Users\91801\AppData\Local\Temp\ipykernel_20612\4205172241.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df6 = df.fillna(method='ffill', axis='columns')
C:\Users\91801\AppData\Local\Temp\ipykernel_20612\4205172241.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df6 = df.fillna(method='ffill', axis='columns')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,Rasmussen Group,Chile,Chile,397.884.0519x718,zunigavanessa@smith.info,2020-08-24 00:00:00,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,Lozano,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23 00:00:00,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,beckycarr@hogan.com,beckycarr@hogan.com
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,Joanna,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17 00:00:00,https://goodwin-ingram.com/
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(283)437-3886x88321,999-728-1637,999-728-1637,999-728-1637,999-728-1637
6,7.0,EA4d384DfDbBf77,Darren,Darren,"Lester, Woodard and Mitchell",Lake Ana,Lake Ana,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24 00:00:00,https://www.le.com/

In [16]:
df6 = df.fillna(method='bfill', axis='columns')
df6.head()

C:\Users\91801\AppData\Local\Temp\ipykernel_20612\2093781745.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df6 = df.fillna(method='bfill', axis='columns')
C:\Users\91801\AppData\Local\Temp\ipykernel_20612\2093781745.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df6 = df.fillna(method='bfill', axis='columns')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,Chile,Chile,397.884.0519x718,397.884.0519x718,zunigavanessa@smith.info,2020-08-24 00:00:00,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,East Jimmychester,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23 00:00:00,http://www.hobbs.com/
2,beckycarr@hogan.com,beckycarr@hogan.com,beckycarr@hogan.com,beckycarr@hogan.com,beckycarr@hogan.com,beckycarr@hogan.com,beckycarr@hogan.com,beckycarr@hogan.com,beckycarr@hogan.com,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,"Martin, Lang and Andrade","Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17 00:00:00,https://goodwin-ingram.com/

In [18]:
df7 = df.fillna(method='ffill', limit = 2)
df7.head(10)

C:\Users\91801\AppData\Local\Temp\ipykernel_20612\3555507922.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df7 = df.fillna(method='ffill', limit = 2)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,Rasmussen Group,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,2.0,1Ef7b82A4CAAD10,Preston,Lozano,Rasmussen Group,East Jimmychester,Djibouti,5153435776,686-620-1820x944,beckycarr@hogan.com,2021-04-23,http://www.hobbs.com/
3,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,beckycarr@hogan.com,2021-04-23,http://www.hobbs.com/
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),(283)437-3886x88321,999-728-1637,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
6,7.0,EA4d384DfDbBf77,Darren,NaN,"Lester, Woodard and Mitchell",Lake Ana,Slovakia (Slovak Republic),(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8.0,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [21]:
df8 = df.interpolate()
df8.head()

C:\Users\91801\AppData\Local\Temp\ipykernel_20612\2222141170.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df8 = df.interpolate()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,2021-04-21,NaN
3,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-04-19,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [25]:
df9 = df.interpolate(method='linear')
df9

C:\Users\91801\AppData\Local\Temp\ipykernel_20612\1151930254.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df9 = df.interpolate(method='polynomial', order=5)

NotImplementedError:

In [28]:
df7 = df.dropna()
df7.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
7,8.0,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/
10,11.0,216E205d6eBb815,Carl,Schroeder,"Oconnell, Meza and Everett",Shannonville,Guernsey,637-854-0256x825,114.336.0784x788,kirksalas@webb.com,2021-10-20,https://simmons-hurley.com/
11,12.0,CEDec94deE6d69B,Jenna,Dodson,"Hoffman, Reed and Mcclain",East Andrea,Vietnam,(041)737-3846,+1-556-888-3485x42608,mark42@robbins.com,2020-11-29,http://www.douglas.net/

In [30]:
df8 = df.dropna(how="all")
df8.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaT,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(283)437-3886x88321,999-728-1637,NaN,NaT,NaN
6,7.0,EA4d384DfDbBf77,Darren,NaN,"Lester, Woodard and Mitchell",Lake Ana,NaN,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8.0,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/
10,11.0,216E205d6eBb815,Carl,Schroeder,"Oconnell, Meza and Everett",Shannonville,Guernsey,637-854-0256x825,114.336.0784x788,kirksalas@webb.com,2021-10-20,https://simmons-hurley.com/

In [40]:
df2 = df.dropna(thresh=1)
df2.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaT,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/