In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('customers-100.csv')

In [3]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/

In [4]:
df1 = df.replace('Chile', 'CH')
df1.head(2)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,CH,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/

In [5]:
df3 = df.replace({
    "First Name": "Sheryl",
    "Country": "Chile"}, "New Value")
df3.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,New Value,Baxter,Rasmussen Group,NaN,New Value,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/

In [6]:
df2 = df.replace('Chile', np.nan)
df2.head(2)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,NaN,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/

In [7]:
df3 = df.replace(["Chile", "Sheryl","Preston"], "New Value")
df3.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,New Value,Baxter,Rasmussen Group,NaN,New Value,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,New Value,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/

In [10]:
df3 = df.replace({
    "Baxter": "No Surname",
    "053d585Ab6b3159": "No Id"})
df3.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,No Surname,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,No Id,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/

In [15]:
df3 = df.replace({'First Name': '[A-Za-z]'}, " ",
					regex= True)
df3.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(283)437-3886x88321,999-728-1637,NaN,NaN,NaN
6,7.0,EA4d384DfDbBf77,,NaN,"Lester, Woodard and Mitchell",Lake Ana,NaN,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,24-08-2021,https://www.le.com/
7,8.0,0e04AFde9f225dE,,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,12-04-2021,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,13-01-2020,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,08-11-2021,https://arias.com/

In [18]:
df3 = df.replace(["Chile", "Sheryl","Preston"], [1,2,3])
df3.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,2,Baxter,Rasmussen Group,NaN,1,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,3,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/