In [1]:
import pandas as pd

# Group by

In [2]:
df = pd.DataFrame({
    "City": ['Mumbai','Mumbai','Mumbai', 'Bhubaneswar', 'Bhubaneswar', 'Bhubaneswar', 'Bengaluru','Bengaluru','Bengaluru'],
    "temp": [12,13,19,41,31,40,38,29,40],
    "wind": [5,6,23,5,8,9,1,9,6]})
df

          City  temp  wind
0       Mumbai    12     5
1       Mumbai    13     6
2       Mumbai    19    23
3  Bhubaneswar    41     5
4  Bhubaneswar    31     8
5  Bhubaneswar    40     9
6    Bengaluru    38     1
7    Bengaluru    29     9
8    Bengaluru    40     6

In [13]:
gr = df.groupby('City')
gr

In [14]:
for city, cityDf in gr:
    print(city)
    print(cityDf)

Bengaluru
        City  temp  wind
6  Bengaluru    38     1
7  Bengaluru    29     9
8  Bengaluru    40     6
Bhubaneswar
          City  temp  wind
3  Bhubaneswar    41     5
4  Bhubaneswar    31     8
5  Bhubaneswar    40     9
Mumbai
     City  temp  wind
0  Mumbai    12     5
1  Mumbai    13     6
2  Mumbai    19    23

In [15]:
gr.get_group("Bhubaneswar")

          City  temp  wind
3  Bhubaneswar    41     5
4  Bhubaneswar    31     8
5  Bhubaneswar    40     9

In [16]:
gr.max()

             temp  wind
City
Bengaluru      40     9
Bhubaneswar    41     9
Mumbai         19    23

In [17]:
gr.min()

             temp  wind
City
Bengaluru      29     1
Bhubaneswar    31     5
Mumbai         12     5

In [18]:
gr.mean()

                  temp       wind
City
Bengaluru    35.666667   5.333333
Bhubaneswar  37.333333   7.333333
Mumbai       14.666667  11.333333

In [19]:
gr.describe()

             temp                                                     wind  \
            count       mean       std   min   25%   50%   75%   max count
City
Bengaluru     3.0  35.666667  5.859465  29.0  33.5  38.0  39.0  40.0   3.0
Bhubaneswar   3.0  37.333333  5.507571  31.0  35.5  40.0  40.5  41.0   3.0
Mumbai        3.0  14.666667  3.785939  12.0  12.5  13.0  16.0  19.0   3.0


                  mean        std  min  25%  50%   75%   max
City
Bengaluru     5.333333   4.041452  1.0  3.5  6.0   7.5   9.0
Bhubaneswar   7.333333   2.081666  5.0  6.5  8.0   8.5   9.0
Mumbai       11.333333  10.115994  5.0  5.5  6.0  14.5  23.0

In [10]:
gr1 = df.groupby('wind')

In [11]:
for speed, group in gr1:
    print(speed)
    print(group)

1
        City  temp  wind
6  Bengaluru    38     1
5
          City  temp  wind
0       Mumbai    12     5
3  Bhubaneswar    41     5
6
        City  temp  wind
1     Mumbai    13     6
8  Bengaluru    40     6
8
          City  temp  wind
4  Bhubaneswar    31     8
9
          City  temp  wind
5  Bhubaneswar    40     9
7    Bengaluru    29     9
23
     City  temp  wind
2  Mumbai    19    23

# Concatenation

In [20]:
weather1 = pd.DataFrame({
    "City": ['Mumbai', 'Bhubaneswar','Bengaluru'],
    "temp": [12,13,19],
    "wind": [5,6,23]})
weather1

          City  temp  wind
0       Mumbai    12     5
1  Bhubaneswar    13     6
2    Bengaluru    19    23

In [21]:
weather2 = pd.DataFrame({
    "City": ['Chennai', 'Delhi','Hyderabad'],
    "temp": [23,23,29],
    "wind": [5,6,9]})
weather2

        City  temp  wind
0    Chennai    23     5
1      Delhi    23     6
2  Hyderabad    29     9

In [22]:
df = pd.concat([weather1, weather2])
df

          City  temp  wind
0       Mumbai    12     5
1  Bhubaneswar    13     6
2    Bengaluru    19    23
0      Chennai    23     5
1        Delhi    23     6
2    Hyderabad    29     9

In [23]:
df = pd.concat([weather1, weather2], ignore_index=True)
df

          City  temp  wind
0       Mumbai    12     5
1  Bhubaneswar    13     6
2    Bengaluru    19    23
3      Chennai    23     5
4        Delhi    23     6
5    Hyderabad    29     9

In [24]:
df = pd.concat([weather1, weather2], keys=["DF1", "DF2"])
df

              City  temp  wind
DF1 0       Mumbai    12     5
    1  Bhubaneswar    13     6
    2    Bengaluru    19    23
DF2 0      Chennai    23     5
    1        Delhi    23     6
    2    Hyderabad    29     9

In [25]:
df.loc['DF2']

        City  temp  wind
0    Chennai    23     5
1      Delhi    23     6
2  Hyderabad    29     9

In [26]:
df = pd.concat([weather1, weather2], axis= 1)
df

          City  temp  wind       City  temp  wind
0       Mumbai    12     5    Chennai    23     5
1  Bhubaneswar    13     6      Delhi    23     6
2    Bengaluru    19    23  Hyderabad    29     9

In [27]:
df = pd.concat([weather1, weather2], axis= 0)
df

          City  temp  wind
0       Mumbai    12     5
1  Bhubaneswar    13     6
2    Bengaluru    19    23
0      Chennai    23     5
1        Delhi    23     6
2    Hyderabad    29     9

In [28]:
df1 = pd.DataFrame({
    "City": ['Mumbai', 'Bhubaneswar','Bengaluru'],
    "temp": [12,13,19],
    "wind": [5,6,23]}, index = [1,2,3])
df1

          City  temp  wind
1       Mumbai    12     5
2  Bhubaneswar    13     6
3    Bengaluru    19    23

In [29]:
df2 = pd.DataFrame({
    "City": ['Mumbai', 'Bhubaneswar','Bengaluru'],
    "temp": [12,13,19],
    "wind": [5,6,23]}, index = [2,1,3])
df2

          City  temp  wind
2       Mumbai    12     5
1  Bhubaneswar    13     6
3    Bengaluru    19    23

In [30]:
df = pd.concat([df1,df2], axis=1)
df

          City  temp  wind         City  temp  wind
1       Mumbai    12     5  Bhubaneswar    13     6
2  Bhubaneswar    13     6       Mumbai    12     5
3    Bengaluru    19    23    Bengaluru    19    23