In [1]:
import pandas as pd

In [8]:
s= pd.Series(['A','B','C'])

In [9]:
df1 = pd.DataFrame({
    "City": ['Mumbai', 'Bhubaneswar','Bengaluru'],
    "temp": [12,13,19],
    "wind": [5,6,23]})

In [11]:
df = pd.concat([df1,s], axis=1)
df

          City  temp  wind  0
0       Mumbai    12     5  A
1  Bhubaneswar    13     6  B
2    Bengaluru    19    23  C

# Merge

In [35]:
temp = pd.DataFrame({
    "City": ['Mumbai', 'Bhubaneswar','Bengaluru', 'Kolkata'],
    "temp": [12,13,19, 30]})
temp

          City  temp
0       Mumbai    12
1  Bhubaneswar    13
2    Bengaluru    19
3      Kolkata    30

In [36]:
wind = pd.DataFrame({
    "City": ['Mumbai', 'Bhubaneswar','Delhi'],
    "wind": [5,6,23]})
wind

          City  wind
0       Mumbai     5
1  Bhubaneswar     6
2        Delhi    23

In [37]:
df = pd.merge(temp, wind, on='City')
df

          City  temp  wind
0       Mumbai    12     5
1  Bhubaneswar    13     6

In [21]:
df = pd.merge(temp, wind, on='City', how="left")
df

          City  temp  wind
0       Mumbai    12   5.0
1  Bhubaneswar    13   6.0
2    Bengaluru    19   NaN
3      Kolkata    30   NaN

In [22]:
df = pd.merge(temp, wind, on='City', how="right")
df

          City  temp  wind
0       Mumbai  12.0     5
1  Bhubaneswar  13.0     6
2        Delhi   NaN    23

In [23]:
df = pd.merge(temp, wind, on='City', how="outer")
df

          City  temp  wind
0    Bengaluru  19.0   NaN
1  Bhubaneswar  13.0   6.0
2        Delhi   NaN  23.0
3      Kolkata  30.0   NaN
4       Mumbai  12.0   5.0

In [24]:
df = pd.merge(temp, wind, on='City', how="outer", indicator=True)
df

          City  temp  wind      _merge
0    Bengaluru  19.0   NaN   left_only
1  Bhubaneswar  13.0   6.0        both
2        Delhi   NaN  23.0  right_only
3      Kolkata  30.0   NaN   left_only
4       Mumbai  12.0   5.0        both

In [25]:
df = pd.merge(temp, wind, on='City', how="left", indicator=True)
df

          City  temp  wind     _merge
0       Mumbai    12   5.0       both
1  Bhubaneswar    13   6.0       both
2    Bengaluru    19   NaN  left_only
3      Kolkata    30   NaN  left_only

In [31]:
df = pd.merge(temp, wind, on='City', how="left", suffixes=(False, False))
df

          City  temp  wind
0       Mumbai    12   5.0
1  Bhubaneswar    13   6.0
2    Bengaluru    19   NaN
3      Kolkata    30   NaN

In [42]:
data = {
    'Employee': ['A', 'B', 'C', 'A', 'B', 'C'],
    'Department': ['HR', 'HR', 'HR', 'IT', 'IT', 'IT'],
    'Year': [2022, 2022, 2022, 2023, 2023, 2023],
    'Salary': [40000, 42000, 41000, 45000, 47000, 46000],
    'Bonus': [2000, 2100, 1900, 2500, 2700, 2600]
}

df = pd.DataFrame(data)
df

  Employee Department  Year  Salary  Bonus
0        A         HR  2022   40000   2000
1        B         HR  2022   42000   2100
2        C         HR  2022   41000   1900
3        A         IT  2023   45000   2500
4        B         IT  2023   47000   2700
5        C         IT  2023   46000   2600

In [43]:
pivot_df = df.pivot(index='Employee', columns='Year', values='Salary')
pivot_df

Year       2022   2023
Employee
A         40000  45000
B         42000  47000
C         41000  46000

In [44]:
pivot_table_df = df.pivot_table(
    index='Employee',
    columns='Year',
    values='Salary',
)
pivot_table_df

Year         2022     2023
Employee
A         40000.0  45000.0
B         42000.0  47000.0
C         41000.0  46000.0

In [53]:
pivot_table_df = df.pivot_table(
    index='Employee',
    columns='Year',
    values='Salary',
    aggfunc='sum',     
    fill_value=0,      
    margins=True,    
    margins_name='Total Salary'
)
pivot_table_df

Year            2022    2023  Total Salary
Employee
A              40000   45000         85000
B              42000   47000         89000
C              41000   46000         87000
Total Salary  123000  138000        261000