In [3]:
import pandas as pd
import numpy as np

In [4]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2 = np.array([[10,20,30,40],[50,60,70,80]])
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [7]:
a = pd.concat([arr1,arr2])

TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid

In [8]:
data = {
    'Employee': ['A', 'B', 'C', 'A', 'B', 'C'],
    'Department': ['HR', 'HR', 'HR', 'IT', 'IT', 'IT'],
    'Year': [2022, 2022, 2022, 2023, 2023, 2023],
    'Salary': [40000, 42000, 41000, 45000, 47000, 46000],
    'Bonus': [2000, 2100, 1900, 2500, 2700, 2600]
}

df = pd.DataFrame(data)
df

  Employee Department  Year  Salary  Bonus
0        A         HR  2022   40000   2000
1        B         HR  2022   42000   2100
2        C         HR  2022   41000   1900
3        A         IT  2023   45000   2500
4        B         IT  2023   47000   2700
5        C         IT  2023   46000   2600

In [10]:
melt_df = pd.melt(
    df,
    id_vars=['Employee', 'Department'],   
    value_vars=['Salary', 'Bonus', 'Year'],       
    var_name='New Col',                  
    value_name='Amount'                   
)
melt_df

   Employee Department New Col  Amount
0         A         HR  Salary   40000
1         B         HR  Salary   42000
2         C         HR  Salary   41000
3         A         IT  Salary   45000
4         B         IT  Salary   47000
5         C         IT  Salary   46000
6         A         HR   Bonus    2000
7         B         HR   Bonus    2100
8         C         HR   Bonus    1900
9         A         IT   Bonus    2500
10        B         IT   Bonus    2700
11        C         IT   Bonus    2600
12        A         HR    Year    2022
13        B         HR    Year    2022
14        C         HR    Year    2022
15        A         IT    Year    2023
16        B         IT    Year    2023
17        C         IT    Year    2023

In [16]:
df.rename(columns={'Employee':'Emp Name', 'Salary': 'Sal'}, inplace=True)
df

  Emp Name Department  Year    Sal  Bonus
0        A         HR  2022  40000   2000
1        B         HR  2022  42000   2100
2        C         HR  2022  41000   1900
3        A         IT  2023  45000   2500
4        B         IT  2023  47000   2700
5        C         IT  2023  46000   2600

In [20]:
data = {
    'Employee': ['A','A', 'B', 'C', 'A', 'B', 'C'],
    'Department': ['HR','HR', 'HR', 'HR', 'IT', 'IT', 'IT'],
    'Year': [2022,2022, 2022, 2022, 2023, 2023, 2023],
    'Salary': [40000,40000, 42000, 41000, 45000, 47000, 46000],
    'Bonus': [2000,2000, 2100, 1900, 2500, 2700, 2600]
}
df3 = pd.DataFrame(data)
df3

  Employee Department  Year  Salary  Bonus
0        A         HR  2022   40000   2000
1        A         HR  2022   40000   2000
2        B         HR  2022   42000   2100
3        C         HR  2022   41000   1900
4        A         IT  2023   45000   2500
5        B         IT  2023   47000   2700
6        C         IT  2023   46000   2600

In [21]:
df3.drop_duplicates(inplace=True)
df3

  Employee Department  Year  Salary  Bonus
0        A         HR  2022   40000   2000
2        B         HR  2022   42000   2100
3        C         HR  2022   41000   1900
4        A         IT  2023   45000   2500
5        B         IT  2023   47000   2700
6        C         IT  2023   46000   2600

In [22]:
def add(a,b):
    return a+b

print(add(10,20))

sum = lambda a,b: a+b
sum(10,10)

30

20

In [23]:
df['New'] = df['Year'].apply(lambda x: x+1)
df

  Emp Name Department  Year    Sal  Bonus   New
0        A         HR  2022  40000   2000  2023
1        B         HR  2022  42000   2100  2023
2        C         HR  2022  41000   1900  2023
3        A         IT  2023  45000   2500  2024
4        B         IT  2023  47000   2700  2024
5        C         IT  2023  46000   2600  2024

In [25]:
df.sort_values('Sal', ascending=True, inplace=True)
df

  Emp Name Department  Year    Sal  Bonus   New
0        A         HR  2022  40000   2000  2023
2        C         HR  2022  41000   1900  2023
1        B         HR  2022  42000   2100  2023
3        A         IT  2023  45000   2500  2024
5        C         IT  2023  46000   2600  2024
4        B         IT  2023  47000   2700  2024

In [26]:
df.sort_values('Sal', ascending=False, inplace=True)
df

  Emp Name Department  Year    Sal  Bonus   New
4        B         IT  2023  47000   2700  2024
5        C         IT  2023  46000   2600  2024
3        A         IT  2023  45000   2500  2024
1        B         HR  2022  42000   2100  2023
2        C         HR  2022  41000   1900  2023
0        A         HR  2022  40000   2000  2023

In [28]:
df3.sort_values('Employee', ascending=True, inplace=True)
df3

  Employee Department  Year  Salary  Bonus
0        A         HR  2022   40000   2000
4        A         IT  2023   45000   2500
2        B         HR  2022   42000   2100
5        B         IT  2023   47000   2700
3        C         HR  2022   41000   1900
6        C         IT  2023   46000   2600